import Layout from "../layouts/Layout";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import SEO from "./SEO";
import founder from "../assets/founder.png";

// Shared chrome for long-form pieces. Reading measure is deliberately
// narrower than the product pages (~66ch) and the type larger — these are
// read start to finish rather than scanned, which is the opposite of how
// everything else on this site is used.
export default function InsightLayout({
  title,
  description,
  path,
  kicker,
  dek,
  date,
  datePublished,
  closing,
  children,
}) {
  const url = `https://queloshieldx.in${path}`;
  // Per-article card generated by `npm run og` and committed to public/og/.
  const ogImage = `/og/${path.split("/").pop()}.png`;

  // Article schema, not the site-wide Organization schema — these are the only
  // pages with a named author and a publication date, which is what lets a
  // search engine treat them as authored writing rather than product copy.
  const schema = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: title,
    description,
    datePublished,
    dateModified: datePublished,
    author: {
      "@type": "Person",
      name: "Sudarson Radhakrishnan",
      jobTitle: "Founder & CEO",
      worksFor: { "@type": "Organization", name: "ShieldX" },
    },
    publisher: {
      "@type": "Organization",
      name: "ShieldX",
      url: "https://queloshieldx.in",
    },
    mainEntityOfPage: { "@type": "WebPage", "@id": url },
    image: `https://queloshieldx.in${ogImage}`,
  };

  return (
    <Layout>
      <SEO
        title={title}
        description={description}
        path={path}
        type="article"
        ogImage={ogImage}
      />

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />

      <article className="max-w-[680px] mx-auto px-8 pt-[120px] pb-32">

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: "easeOut" }}
        >
          <Link to="/insights" className="inline-flex items-center gap-2 text-white/35 text-xs hover:text-white/65 transition-colors mb-9">
            ← Insights
          </Link>

          <div className="text-[11px] text-emerald-400/60 tracking-[0.2em] mb-5">{kicker}</div>

          <h1 className="text-[32px] md:text-[42px] font-semibold leading-[1.15] tracking-tight mb-6"
            style={{ textWrap: "balance" }}>
            {title}
          </h1>

          {dek && (
            <p className="text-white/60 text-[18px] leading-relaxed mb-9">{dek}</p>
          )}

          <div className="flex items-center gap-3.5 pb-9 mb-11 border-b border-white/[0.09]">
            <img src={founder} alt="" aria-hidden="true"
              className="w-9 h-9 rounded-full object-cover border border-white/[0.12]" />
            <div className="text-[13px]">
              <span className="text-white/70">Sudarson Radhakrishnan</span>
              <span className="text-white/30"> · Founder &amp; CEO</span>
              {date && <span className="text-white/25"> · {date}</span>}
            </div>
          </div>
        </motion.div>

        <div className="insight-body">{children}</div>

        <div className="border-t border-white/[0.09] mt-16 pt-9">
          <p className="text-white/45 text-[14px] leading-relaxed mb-6">
            {closing || (
              <>
                ShieldX is decisioning infrastructure for collections. The
                commitments described here are published in full as the
                Neutrality Charter.
              </>
            )}
          </p>
          <div className="flex flex-wrap items-center gap-x-6 gap-y-3 text-[13px]">
            <Link to="/neutrality" className="text-emerald-400/75 hover:text-emerald-400 transition-colors">
              Read the Neutrality Charter →
            </Link>
            <Link to="/demo" className="text-white/45 hover:text-white/75 transition-colors">
              Request a walkthrough →
            </Link>
          </div>
        </div>
      </article>

      <style>{`
        .insight-body p {
          color: rgba(255,255,255,0.66);
          font-size: 16.5px;
          line-height: 1.85;
          margin-bottom: 1.55em;
        }
        .insight-body h2 {
          color: #fff;
          font-size: 21px;
          font-weight: 600;
          line-height: 1.35;
          margin: 2.6em 0 0.9em;
          text-wrap: balance;
        }
        .insight-body strong { color: rgba(255,255,255,0.92); font-weight: 600; }
        .insight-body a {
          color: rgba(52,211,153,0.85);
          text-decoration: underline;
          text-underline-offset: 3px;
          text-decoration-color: rgba(52,211,153,0.35);
          transition: color 0.2s, text-decoration-color 0.2s;
        }
        .insight-body a:hover {
          color: rgb(52,211,153);
          text-decoration-color: rgba(52,211,153,0.7);
        }
        /* Standing note that the piece tracks a moving document. Set apart from
           body copy so a returning reader can see the currency claim without
           re-reading the opening. */
        .insight-body p.insight-note {
          font-size: 13.5px;
          line-height: 1.65;
          color: rgba(255,255,255,0.42);
          border-left: 2px solid rgba(255,255,255,0.12);
          padding-left: 1.1em;
          margin-bottom: 2.4em;
        }
        .insight-body em { color: rgba(255,255,255,0.78); }
        .insight-body ul { margin: 0 0 1.55em; padding-left: 0; list-style: none; }
        .insight-body li {
          color: rgba(255,255,255,0.66);
          font-size: 16.5px;
          line-height: 1.8;
          margin-bottom: 0.75em;
          padding-left: 1.5em;
          position: relative;
        }
        .insight-body li::before {
          content: "—";
          position: absolute;
          left: 0;
          color: rgba(52,211,153,0.5);
        }
        .insight-body blockquote {
          margin: 2.2em 0;
          padding-left: 1.5em;
          border-left: 2px solid rgba(52,211,153,0.4);
          color: rgba(255,255,255,0.8);
          font-size: 19px;
          line-height: 1.65;
        }
      `}</style>
    </Layout>
  );
}
