import Layout from "../layouts/Layout";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import SEO from "./SEO";
import founder from "../assets/founder.png";

// Shared chrome for long-form pieces. Reading measure is deliberately
// narrower than the product pages (~66ch) and the type larger — these are
// read start to finish rather than scanned, which is the opposite of how
// everything else on this site is used.
export default function InsightLayout({
  title,
  description,
  path,
  kicker,
  dek,
  date,
  datePublished,
  closing,
  children,
}) {
  const url = `https://queloshieldx.in${path}`;
  // Per-article card generated by `npm run og` and committed to public/og/.
  const ogImage = `/og/${path.split("/").pop()}.png`;

  // Article schema, not the site-wide Organization schema — these are the only
  // pages with a named author and a publication date, which is what lets a
  // search engine treat them as authored writing rather than product copy.
  const schema = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: title,
    description,
    datePublished,
    dateModified: datePublished,
    author: {
      "@type": "Person",
      name: "Sudarson Radhakrishnan",
      jobTitle: "Founder & CEO",
      worksFor: { "@type": "Organization", name: "ShieldX" },
    },
    publisher: {
      "@type": "Organization",
      name: "ShieldX",
      url: "https://queloshieldx.in",
    },
    mainEntityOfPage: { "@type": "WebPage", "@id": url },
    image: `https://queloshieldx.in${ogImage}`,
  };

  return (
    <Layout>
      <SEO
        title={title}
        description={description}
        path={path}
        type="article"
        ogImage={ogImage}
        author="Sudarson Radhakrishnan"
        publishedTime={datePublished}
        section={kicker}
      />

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />

      {/* Long-form pieces render on a light ground while the nav and footer stay
          dark. These are read start to finish rather than scanned, and the shift
          marks a real distinction: product pages are product, insight pieces are
          documents. `main` sits above Layout's fixed glow layers, so this band
          paints over them cleanly. */}
      <div className="insight-surface">
      <article className="max-w-[680px] mx-auto px-8 pt-[120px] pb-32">

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: "easeOut" }}
        >
          <Link to="/insights" className="insight-back inline-flex items-center gap-2 text-xs mb-9">
            ← Insights
          </Link>

          <div className="insight-kicker text-[11px] tracking-[0.2em] mb-5">{kicker}</div>

          <h1 className="insight-title text-[32px] md:text-[42px] font-semibold leading-[1.15] tracking-tight mb-6"
            style={{ textWrap: "balance" }}>
            {title}
          </h1>

          {dek && (
            <p className="insight-dek text-[18px] leading-relaxed mb-9">{dek}</p>
          )}

          <div className="insight-byline flex items-center gap-3.5 pb-9 mb-11">
            <img src={founder} alt="" aria-hidden="true"
              className="w-9 h-9 rounded-full object-cover" />
            <div className="text-[13px]">
              <strong>Sudarson Radhakrishnan</strong>
              <span> · Founder &amp; CEO</span>
              {date && <span> · {date}</span>}
            </div>
          </div>
        </motion.div>

        <div className="insight-body">{children}</div>

        <div className="insight-close mt-16 pt-9">
          <p className="text-[14px] leading-relaxed mb-6">
            {closing || (
              <>
                ShieldX is decisioning infrastructure for collections. The
                commitments described here are published in full as the
                Neutrality Charter.
              </>
            )}
          </p>
          <div className="flex flex-wrap items-center gap-x-6 gap-y-3 text-[13px]">
            <Link to="/neutrality" className="insight-cta">
              Read the Neutrality Charter →
            </Link>
            <Link to="/demo" className="insight-cta muted">
              Request a walkthrough →
            </Link>
          </div>
        </div>
        </article>
      </div>
    </Layout>
  );
}
